### ISSUE TITLE
Incremental Development, Week 2, Sunday Roll Call

### ISSUE THREAD

**Issue by Fatihayoz** [HackYourFutureBelgium/class-13-14#110]
Leave a comment with these two things:

1. A summary of your week using only emojis
2. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by inggritenovaleta** [comment]
1. :upside_down_face: :blush: :raised_hands: :muscle: :technologist:
2. We are in this together! We can do it :rocket:. So happy to be here. Thank you, everyone!

**Comment by zehrayelkenci** [comment]
Good morning to everyone :upside_down_face: cold_face 

:nerd_face:
--

**Comment by iLienstAr** [comment]
1. 💻 🚶‍♀️ 💬 🦄 ☕ 
2. Our ☕ morning session has filled me with good energy! Thank you for all the attendees.

**Comment by erkamguresen** [comment]
Good morning everyone....
:nerd_face: :computer:
--

**Comment by kilicf** [comment]
1. 💻 ⌛ 👨‍💻 

2. Good Morning... Thanks everyone for everything!

**Comment by Enakhimionsam** [comment]
:+1:

**Comment by emelysalmeron** [comment]
1. 😄 🖱️ 👍🏼 
2. Second week! Here we go !!!

**Comment by victoriayerm** [comment]
💻😊

**Comment by zaraana** [comment]
👋

This week has been so long! 
😷🥶🤒🤒🛌👩‍💻🛌👩‍💻

Nothing can stop us we're all the way up💪💪💪

**Comment by Fatihayoz** [comment]
:student: :computer: :+1:

**Comment by gustavoaespitia** [comment]
💪 💪
_**Enjoy this week**_

**Comment by alinamarasca** [comment]
:seedling: :factory_worker: :palm_tree: :office_worker:

**Comment by Mika215** [comment]
1. :face_with_thermometer: 
2. I am so grateful for your patience and cooperation

**Comment by NasratullahHussaini** [comment]
:satisfied:
happy to be here this week also

**Comment by Cyngyz** [comment]
:runner:  :partying_face: :birthday:

**Comment by perezrei** [comment]
1- 😅 🙃 🤔 😌 😏 💪
2- No questions for now

**Comment by sabanyelkenci** [comment]
Hi everyone :hand:

**Comment by rago89** [comment]
:smiley: :mask: :nerd_face:

**Comment by IrinaSing** [comment]
:computer: :crystal_ball: :computer: :jigsaw: :computer: :shopping_cart: :computer: :smiley:
