### ISSUE TITLE
Incremental Development , week 2, Sunday Roll Call

### ISSUE THREAD

**Issue by Mika215** [HackYourFutureBelgium/class-13-14#111]
Leave a comment with these two things:

1. :face_with_thermometer: 
2. I am so grateful for your patience and cooperation 

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by colevandersWands** [comment]
@Mika215 thanks for making a roll-call.  This week @Fatihayoz stepped in first with #110, closing this as a duplicate

**Comment by Mika215** [comment]
@colevandersWands  Yeah, you are right.
I have lately noticed that and I was wondering how to  delete it back.

Thanks
