### ISSUE TITLE
Collaborator in the project, but can't assign issue to myself

### ISSUE THREAD

**Issue by victoriayerm** [HackYourFutureBelgium/class-13-14#113]
I mentioned as a collaborator in the project, but I could not assign issues to myself - was not active, and I could not create a branch, so I had to PR from my fork. Why? The rest of the collaborators could assign themselves. Link to the group project: https://github.com/perezrei/loruki-website

**Comment by snicoll** [comment]
So we answered this one in class. If the repository owner sent you an invite, make sure to review the email and click on the "Accept Invitation" button. Until you accept the invitation, you won't get any specific rights.

The owner of the repo can review collaborators, add/remove them and resend invitations if necessary. For more details, please check [the official documentation](https://docs.github.com/en/github/administering-a-repository/managing-teams-and-people-with-access-to-your-repository).

**Comment by victoriayerm** [comment]
Yes, thanks!
