### ISSUE TITLE
Group 4: Hack Your Future Belgium Website

### ISSUE THREAD

**Issue by inggritenovaleta** [HackYourFutureBelgium/class-13-14#115]
- [x] [repo](https://github.com/inggritenovaleta/hackyourfuture-g4)
- [x] [live demo](https://inggritenovaleta.github.io/hackyourfuture-g4/)
- [/planning](https://github.com/_/_/tree/master/planning)
  - [x] communication plan
  - [x] constraints
  - [x] backlog
  - [x] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/inggritenovaleta/hackyourfuture-g4/projects/1)
- [x] no JavaScript!

**Comment by alinamarasca** [comment]
add  week-3 too! [week 2 description](https://github.com/HackYourFutureBelgium/incremental-development#week-2)
