### ISSUE TITLE
Group-3: Hack Your Future Belgium Website

### ISSUE THREAD

**Issue by Fatihayoz** [HackYourFutureBelgium/class-13-14#117]
Hey :smile:

We are Group-3:

- [Gustavo](https://github.com/gustavoaespitia): Team Leader
- [Fatih](https://github.com/Fatihayoz): Repository Owner
- [Reinaldo](https://github.com/perezrei): Collaborator
- [Victoria](https://github.com/victoriayerm): Collaborator

**Description:** In this project, we will make reverse-engineering of www.hackyourfuture.be

- [x] [repo](https://github.com/Fatihayoz/HYF-Website) (with a complete README)
- [x] [live demo](https://fatihayoz.github.io/HYF-Website/) (GitHub Pages, not Netlify)
- [/planning](https://github.com/Fatihayoz/HYF-Website/tree/main/planning)
  - [x] communication plan
  - [x] constraints
  - [x] backlog
  - [x] development strategy
  - [x] retrospective
- [x] [project board](https://github.com/Fatihayoz/HYF-Website/projects/1)
- [x] no JavaScript!

**Comment by Fatihayoz** [comment]
Link to project board added.

**Comment by Fatihayoz** [comment]
Repo (with README.md), constraints added.

**Comment by Fatihayoz** [comment]
Live demo added

**Comment by Fatihayoz** [comment]
Communication plan, backlog, development strategy added.
Project board set.

**Comment by Fatihayoz** [comment]
demo link added

**Comment by perezrei** [comment]
add team leader and collaborators

**Comment by Fatihayoz** [comment]
"no JavaScript!" checked

**Comment by Fatihayoz** [comment]
"retrospective" checked
