### ISSUE TITLE
Mika215: incremental-development,week 2

### ISSUE THREAD

**Issue by Mika215** [HackYourFutureBelgium/class-13-14#125]
> [module repository](https://github.com/Mika215/incremental-development)

Study Plan

---

Week X

- [ ] started the exercises
- [ ] [project issue](https://github.com/HackYourFutureBelgium/class-13-14/issues/116)

**Comment by colevandersWands** [comment]
👋 @Mika215 , could you move your week 2 check-in into the same one as your week 1 check-in? This helps you keep track of all your study for this module in one place, like @zehrayelkenci did in #106

**Comment by Mika215** [comment]
> 👋 @Mika215 , could you move your week 2 check-in into the same one as your week 1 check-in? This helps you keep track of all your study for this module in one place, like @zehrayelkenci did in #106

Hello @colevandersWands , i have tried to keep the two weeks checkin in one.
I am sorry for my delayed action( still with a lot of errors ).
