### ISSUE TITLE
rago89: UX/UI design, week 1

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-13-14#145]
> [module repository](https://github.com/rago89/ux-ui-design)

## Study Plan

---
<details>
<summary>Empathy for Developers</summary>
<br>

- [x] - [What is Empathy?](https://codingwithempathy.com/2016/05/03/empathy-an-essential-skill-in-software-development/)
- [x] - [Empathy can be Learned](https://medium.com/old-code-new-tricks/software-development-on-the-empathy-spectrum-f77596faeabc)
- [x] - [Inclusion](http://danielwestheide.com/blog/2017/01/16/the-empathic-programmer.html)

- [x] - [Use Empathy to Build Software Products](https://www.youtube.com/watch?v=mlPg6x8CRfk)

- [x] - [Soft Skills for Hardcore Developers](https://podtail.com/podcast/make-better-software/ed-finkler-soft-skills-for-hardcore-developers/)

- [x] - [EDD - Empathy Driven Development](https://www.infoq.com/news/2015/06/empathy-development)
- [x] - [Integrating Empathy 1](https://thenewstack.io/empathy-secret-sauce-good-software-development/)
- [x] - [Integrating Empathy 2](https://simpleprogrammer.com/empathy-software-developers/)
- [x] - [Some Practical Tips](https://truefit.io/blog/how-to-instill-empathy-in-the-software-development-process)

</details>
<details>
<summary>User Personas</summary>
<br>

- [x] - [interaction-design.org](https://www.youtube.com/watch?v=XnG4c4gXaQY)
- [x] - [Robert Smith](https://www.youtube.com/watch?v=vZ578SqL1oA)
- [x] - [Abnux](https://www.youtube.com/watch?v=GaEdg9zTdB8)

</details>
<details>
<summary>Design Thinking</summary>
<br>

- [x] - Design Thinking Process: [Sprouts](https://www.youtube.com/watch?v=_r0VX-aU_T8),[Stanford]

(https://web.stanford.edu/~mshanks/MichaelShanks/files/509554.pdf)
  1. Empathize
  2. Define
  3. Ideate
  4. Prototype
  5. Test

- [ ] - [invisionapp](https://www.invisionapp.com/inside-design/what-is-design-thinking/)
- [ ] - [Creative Confidence (TED)](https://www.ted.com/talks/david_kelley_how_to_build_your_creative_confidence)
- [ ] - [First Step: Noticing (TED)](https://www.ted.com/talks/tony_fadell_the_first_secret_of_design_is_noticing)
- [ ] - [Design Thinking (TED)](https://www.youtube.com/watch?v=Q80wUnju5YA)
- [ ] - [Collaboration & Innovation (TED)](https://www.youtube.com/watch?v=ZBxZC9I6xyk)
- [ ] - [Visualize It (TED)](https://www.youtube.com/watch?v=TPXrheqhTCs)
- [ ] - [interaction-design.org](https://www.interaction-design.org/literature/topics/design-thinking)
- [ ] - [dschool.stanford.edu](https://dschool.stanford.edu/resources)
- [ ] - [The Wallet Challenge](https://medium.com/@erio/bringing-design-thinking-into-the-workplace-the-wallet-design-chall

enge-544c727d3752)

- [ ] - [The Coffee Filter Challenge](https://www.tedxvenlo.com/news/guido-stompff-design-thinking/)
- [ ] - Process Guides:
  - [Design is a Process](https://dschool-old.stanford.edu/sandbox/groups/k12/wiki/c739e/attachments/ade8c/An_Intro_to_DT_Slides_07_10_09.pdf?sessionID=8cbdfc6129ceb041dbad2247ffc9d0112fd0ebce)
  

- [ ] - [Explanatory](https://dschool-old.stanford.edu/sandbox/groups/designresources/wiki/36873/attachments/74b3d/ModeGuideBOOTCAMP2010L.pdf)

</details>
<details>
<summary>Design Thinking for Developers</summary>
<br>

- [x] - [Design Thinking Process](https://www.khomp.com/en/design-thinking-in-software-development/)
- [x] - [9 Tips](https://techeries.com/9-software-development-tips-successfully-incorporate-design-thinking-projects/)
- [x] - [Design Thinking vs. Agile](http://blogs.infor.com/insights/2017/11/outside-the-code-development-with-design-thinking.html)
- [x] - [Waterfall vs Agile vs DT](https://www.artefactgroup.com/articles/post-agile-a-design-thinking-approach-to-software-development/)
- [x] - [Ultimate Guide to UI/UX Design](http://ptgmedia.pearsoncmg.com/images/9780321965516/samplepages/0321965515.pdf)
- [x] - [Big Data & DT](http://www.ibmbigdatahub.com/blog/dynamic-duo-big-data-and-design-thinking)
- [x] - [Longer, Detailed Talk](https://www.youtube.com/watch?v=FtUS1W3HymA)
- [x] - [Beware the User!](https://medium.com/@blakeross/mr-fart-s-favorite-colors-3177a406c775)
- [ ] - next level: [Art Thinking](https://www.fastcompany.com/3019082/coding-is-an-art-software-people-should-learn-art-thinking)

</details>
<details>
<summary>General</summary>
<br>

- [ ] - [designnotes](https://www.designnotes.co/) (huge repository of sites with design resources, inspiration…)
- [ ] - [designinspiration](https://www.designspiration.com/)
- [ ] - [Learn Design with Me](https://www.youtube.com/watch?v=WZQYt5HZ0-E&list=PLDtHAiqIa4wa5MBbE_XDoqY51sAkQnkjt

)

</details>
<details>
<summary>User experience (UX)</summary>
<br>

- [ ] - [uxchecklist.github.io](https://uxchecklist.github.io/) - Complete list of methods and techniques used in UX design
- [ ] - [Jacob Nielsen’s Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/)
- [ ] - [Short videos on YouTube](https://www.youtube.com/c/NNgroup/videos) about UX, UI, explaining all concepts of the design 

field.

- [ ] - [The (condensed) basics of UX and UI design](https://medium.com/hh-design/crash-course-ui-design-25d13ff60962)
- [ ] - [Usability.gov](https://www.usability.gov/index.html)
- [ ] - [UXBooth](https://www.uxbooth.com/)
- [ ] - [UXMovement](https://uxmovement.com/)
- [ ] - [UXCollective](https://uxdesign.cc/)
- [ ] - [InsideDesign by InVision](https://www.invisionapp.com/inside-design/)
- [ ] - [A List Apart](https://alistapart.com/)
- [ ] - [UX Planet](https://uxplanet.org/)
- [ ] - https://spotify.design/stories/process
- [ ] - https://uxmag.com/
- [ ] - https://www.nngroup.com/

</details>

---

### Check-In
Learning about interviews 
#### I Need Help With:
I don't know how to build this format
partner's name needs a way to ?.
Unexpectedly, in their world, ?.
#### What went well?
Going out of my comfort area and learning something really new 
#### What went less well?
Schedule, there isn't a lot of time to meet and build planning
#### Lessons Learned
Empathy is an extremely powerful word
### Sunday Prep Work

https://www.figma.com/file/sCQSksprH1gscL5e8JmRoi/Horeca-Contact-Sharing

How many hours does everyone have? and when are you generally available?

## Week II

- [Figma Horeca contact tracing ](https://www.figma.com/file/sCQSksprH1gscL5e8JmRoi/Horeca-Contact-Sharing)
- [Demo figma horeca  contact tracing](https://www.figma.com/proto/sCQSksprH1gscL5e8JmRoi/Horeca-Contact-Sharing?node-id=0%3A1)

**Comment by colevandersWands** [comment]
> I don't know how to build this format
> partner's name needs a way to ?.
>    Unexpectedly, in their world, ?.

It's a template sentence to write down your interview findings, a finished one might look like:

`Rafael needs a way to find a pair-programming partner.  Unexpectedly in his world he has no internet connection.`

With this format you can nicely lay out the user's needs next to their unique constraints.  After writing this sentence I might decide I need to find a way for you to collaborate on a project by sharing code snippets via SMS

**Comment by colevandersWands** [comment]
And a practical thing, could you move your project checklist to a separate issue and place it on the project board? This is a new thing for 13-14.  Tracking individual projects the same way as group projects will make it easier to review

**Comment by rago89** [comment]
Thanks for the feedback, modifications finished.
