### ISSUE TITLE
Reinaldo Perez: ux-ui-design 

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-13-14#163]
# Week 1

I will learn about Design Thinking and User Empathy by designing a home page for my classmate @sheybusta  that she will develop. The main objective is to understand Sheyla and help her to build the home page she needs.

At the same time she will be collaborating with me by designing my personal home page that I will develop.

Along the way I will explore the world of Open Source Software by selecting a CSS Framework from GitHub, contributing to my classmates home pages, and making a contribution to my CSS Framework's repository.

## My Home Page

- [repo]()
  - with your partner:
  - [ ] README
  - on your own:
  - [x] License
  - [x] Contributor Guidelines
  - [x] Code of Conduct
- [x] [live demo](https://perezrei.github.io)
- [/planning]()
  - with your project partner:
  - [x] interview (your completed interview template)
  - [x] backlog (developed with your partner based on the interview)
  - [x] wireframe (design your site's outline together)
  - on your own:
  - [x] schedule (like communication plan, but for yourself)
  - [ ] constraints (include the CSS framework you chose and why)
  - [ ] development strategy
  - [ ] retrospective
- [ ] [project board]()

## My Contributions

- Home Pages:
  - [ ] [classmate's name](link_to_your_contribution)
  - [ ] [classmate's name](link_to_your_contribution)
  - [ ] [classmate's name](link_to_your_contribution)
  - ... why stop at 3?
- CSS Framework Name:
  - [ ] [describe contribution](link_to_your_contribution)
  - ... why stop at 1?

## Suggested Study

<!---Links to help you through the assignments

<details>
<summary>expand/collapse</summary>
<br>

**Comment by perezrei** [comment]
Changing Suggested Study into a checklist

**Comment by perezrei** [comment]
Improving project description

**Comment by perezrei** [comment]
Fixing live-demo link

**Comment by perezrei** [comment]
# Week 1 Check-In  

### I Need Help With:
Nothing for now. I feel very comfortable with UX design

### What went well?
The communication with my partner. Excellent empathy with her.
 

### What went less well?
The time to see the videos and read more, but It will be more time to do that later.

### Lessons Learned
How to prepare and conduct an interview to create a user persona. Until today, it's been a lot of research and reading besides thinking in the website proposal for my partner. From tomorrow, I think it's going to be more of design and prototype.

**Comment by perezrei** [comment]
## I wanted to make a copy of sunday's assignment because it's related with the module and I had much fun.

![sheyla's card](https://user-images.githubusercontent.com/74242999/110246293-5dfaab00-7f67-11eb-9504-9d41786333cd.png)

**Comment by perezrei** [comment]
Move items to study to a new repo

**Comment by perezrei** [comment]
I wanted to share the design of my website on Figma too:
[My Website](https://www.figma.com/proto/2FgicNZTVK8r1XFRbQufuP/My-Website?node-id=25%3A172&scaling=scale-down-width)

**Comment by perezrei** [comment]
# Week 2 Check-In

### I Need Help With:
I don't have a particular doubt at this moment.

### What went well?
Comfortable with Figma because I have work with design programs, but it's way better for web developing, it’s a powerful tool.

### What went less well?
Last week I did not have time to work on the development of my website which was designed by my partner @sheybust or to make a contribution to my classmates on their projects. I thought that this week we would have the time to do it because the Horeca project looked simple. Although it was easy for me to understand how to use Figma, it obviously took me a while to learn about most of its benefits. 
I will try to catch up with the pending and at the same time prepare me a little with JS.

### Lessons Learned
How to make a web design and prototype with Figma.

**Comment by colevandersWands** [comment]
Home pages are never finished, this is just the beginning : )

**Comment by perezrei** [comment]
Closing module issue
