### ISSUE TITLE
Erkam Guresen:  ux-ui-design, 2 weeks

### ISSUE THREAD

**Issue by erkamguresen** [HackYourFutureBelgium/class-13-14#165]
> [module repository](https://github.com/erkamguresen/ux-ui-design)

Study Plan

## Suggested Study

Links to help you through the assignments

<details>
<summary>expand/collapse</summary>
<br>

You don't need to learn all of this, it's _a lot_ of links.

These links will always be here for you when you need them in the future.

### User Experience and User Interfaces

<details>
<summary>Empathy for Developers</summary>
<br>

- [What is Empathy?](https://codingwithempathy.com/2016/05/03/empathy-an-essential-skill-in-software-development/)
- [Empathy can be Learned](https://medium.com/old-code-new-tricks/software-development-on-the-empathy-spectrum-f77596faeabc)
- [interaction-design.org](https://www.interaction-design.org/literature/article/design-thinking-getting-started-with-empathy)
- [Inclusion](http://danielwestheide.com/blog/2017/01/16/the-empathic-programmer.html)
- [Use Empathy to Build Software Products](https://www.youtube.com/watch?v=mlPg6x8CRfk)
- [Soft Skills for Hardcore Developers](https://podtail.com/podcast/make-better-software/ed-finkler-soft-skills-for-hardcore-developers/)
- [EDD - Empathy Driven Development](https://www.infoq.com/news/2015/06/empathy-development)
- [Integrating Empathy 1](https://thenewstack.io/empathy-secret-sauce-good-software-development/)
- [Integrating Empathy 2](https://simpleprogrammer.com/empathy-software-developers/)
- [Some Practical Tips](https://truefit.io/blog/how-to-instill-empathy-in-the-software-development-process)
- [FreeCodeCamp](https://www.freecodecamp.org/news/how-empathy-makes-you-a-better-software-engineer/)

</details>
<details>
<summary>User Personas</summary>
<br>

- [interaction-design.org](https://www.youtube.com/watch?v=XnG4c4gXaQY)
- [Robert Smith](https://www.youtube.com/watch?v=vZ578SqL1oA)
- [Abnux](https://www.youtube.com/watch?v=GaEdg9zTdB8)

</details>
<details>
<summary>Design Thinking</summary>
<br>

- Design Thinking Process: [Sprouts](https://www.youtube.com/watch?v=_r0VX-aU_T8),[Stanford](https://web.stanford.edu/~mshanks/MichaelShanks/files/509554.pdf)
  1. Empathize
  2. Define
  3. Ideate
  4. Prototype
  5. Test
- [invisionapp](https://www.invisionapp.com/inside-design/what-is-design-thinking/)
- [Creative Confidence (TED)](https://www.ted.com/talks/david_kelley_how_to_build_your_creative_confidence)
- [First Step: Noticing (TED)](https://www.ted.com/talks/tony_fadell_the_first_secret_of_design_is_noticing)
- [Design Thinking (TED)](https://www.youtube.com/watch?v=Q80wUnju5YA)
- [Collaboration & Innovation (TED)](https://www.youtube.com/watch?v=ZBxZC9I6xyk)
- [Visualize It (TED)](https://www.youtube.com/watch?v=TPXrheqhTCs)
- [interaction-design.org](https://www.interaction-design.org/literature/topics/design-thinking)
- [dschool.stanford.edu](https://dschool.stanford.edu/resources)
- [The Wallet Challenge](https://medium.com/@erio/bringing-design-thinking-into-the-workplace-the-wallet-design-challenge-544c727d3752)
- [The Coffee Filter Challenge](https://www.tedxvenlo.com/news/guido-stompff-design-thinking/)
- Process Guides:
  - [Design is a Process](https://dschool-old.stanford.edu/sandbox/groups/k12/wiki/c739e/attachments/ade8c/An_Intro_to_DT_Slides_07_10_09.pdf?sessionID=8cbdfc6129ceb041dbad2247ffc9d0112fd0ebce)
  - [Explanatory](https://dschool-old.stanford.edu/sandbox/groups/designresources/wiki/36873/attachments/74b3d/ModeGuideBOOTCAMP2010L.pdf)

</details>
<details>
<summary>Design Thinking for Developers</summary>
<br>

- [Design Thinking Process](https://www.khomp.com/en/design-thinking-in-software-development/)
- [9 Tips](https://techeries.com/9-software-development-tips-successfully-incorporate-design-thinking-projects/)
- [Design Thinking vs. Agile](http://blogs.infor.com/insights/2017/11/outside-the-code-development-with-design-thinking.html)
- [Waterfall vs Agile vs DT](https://www.artefactgroup.com/articles/post-agile-a-design-thinking-approach-to-software-development/)
- [Ultimate Guide to UI/UX Design](http://ptgmedia.pearsoncmg.com/images/9780321965516/samplepages/0321965515.pdf)
- [Big Data & DT](http://www.ibmbigdatahub.com/blog/dynamic-duo-big-data-and-design-thinking)
- [Longer, Detailed Talk](https://www.youtube.com/watch?v=FtUS1W3HymA)
- [Beware the User!](https://medium.com/@blakeross/mr-fart-s-favorite-colors-3177a406c775)
- next level: [Art Thinking](https://www.fastcompany.com/3019082/coding-is-an-art-software-people-should-learn-art-thinking)

</details>
<details>
<summary>General</summary>
<br>

- [designnotes](https://www.designnotes.co/) (huge repository of sites with design resources, inspiration…)
- [designinspiration](https://www.designspiration.com/)
- [Learn Design with Me](https://www.youtube.com/watch?v=WZQYt5HZ0-E&list=PLDtHAiqIa4wa5MBbE_XDoqY51sAkQnkjt)

</details>
<details>
<summary>User experience (UX)</summary>
<br>

- [uxchecklist.github.io](https://uxchecklist.github.io/) - Complete list of methods and techniques used in UX design
- [Jacob Nielsen’s Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/)
- [Short videos on YouTube](https://www.youtube.com/c/NNgroup/videos) about UX, UI, explaining all concepts of the design field.
- [The (condensed) basics of UX and UI design](https://medium.com/hh-design/crash-course-ui-design-25d13ff60962)
- [Usability.gov](https://www.usability.gov/index.html)
- [UXBooth](https://www.uxbooth.com/)
- [UXMovement](https://uxmovement.com/)
- [UXCollective](https://uxdesign.cc/)
- [InsideDesign by InVision](https://www.invisionapp.com/inside-design/)
- [A List Apart](https://alistapart.com/)
- [UX Planet](https://uxplanet.org/)
- https://spotify.design/stories/process
- https://uxmag.com/
- https://www.nngroup.com/

</details>
<details>
<summary>Gestalt</summary>
<br>

- https://www.canva.com/learn/gestalt-theory/
- [www.87seconds.com - lesson-from-our-designers-gestalt-principles](https://www.87seconds.com/lesson-from-our-designers-gestalt-principles/?gclid=EAIaIQobChMIqbLZoYWz3QIVBrXtCh0kPQiaEAAYASAAEgIRF_D_BwE)
- [interaction-design.org](https://www.interaction-design.org/literature/topics/gestalt-principles)
- [nngroup.com](https://www.nngroup.com/articles/principles-visual-design/) UI Principles
- Conceptual Integrity: [safnet](http://www.safnet.com/writing/tech/2011/11/mythical-man-month-conceptual-integrity.html), [CSEWeb](http://cseweb.ucsd.edu/~wgg/CSE131B/Design/node6.html), [DZone](https://dzone.com/articles/lean-tools-conceptual-0), [deep read](http://www.dcs.warwick.ac.uk/oldmodelling/hi/theses/allan/chapter5.pdf)

</details>
<details>
<summary>Colour</summary>
<br>

- https://color.adobe.com/nl/create
- http://khroma.co/
- https://picular.co/
- http://paletton.com
- https://htmlcolorcodes.com/

</details>
<details>
<summary>Iconography</summary>
<br>

- https://thenounproject.com/
- https://www.flaticon.com/
- https://icons.mono.company/
- https://remixicon.com/

</details>
<details>
<summary>Typography and Fonts</summary>
<br>

- https://fontjoy.com/
- https://fonts.google.com/
- https://www.grillitype.com/free_trials
- https://www.fontsquirrel.com/
- https://www.supremo.co.uk/typeterms/
- https://velvetyne.fr/
- https://www.fonts.ninja/ - Try and discover fonts
- https://betterwebtype.com/web-typography-resources/ - Everything you need to know about web typography
- https://typographyhandbook.com/
- https://www.fontshop.com/glossary - All the terms of typography
- https://typespiration.com/ - Collection and inspiration of typography combinations

</details>
<details>
<summary>Style Guides</summary>
<br>

- [Style Guide Guide](https://bradfrost.github.io/style-guide-guide/) by Brad Frost

</details>
<details>
<summary>Accessibility</summary>
<br>

- https://hackyourfuture.github.io/study/#/html-css/accessibility
- https://www.w3.org/WAI/WCAG21/quickref/
- https://www.w3.org/WAI/standards-guidelines/wcag/
- https://webaim.org/
- https://www.microsoft.com/design/inclusive/
- https://accessibility-for-teams.com/
- https://www.a11yproject.com/
- https://www.nngroup.com/articles/keyboard-accessibility/
- https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/
- https://wave.webaim.org/ - Browser plugin
- https://chrome.google.com/webstore/detail/arc-toolkit/chdkkkccnlfncngelccgbgfmjebmkmce?hl=en - Chrome extension
- https://developers.google.com/web/tools/lighthouse - Chrome dev tool
- https://www.deque.com/axe/ - Chrome extension

</details>
<details>
<summary>Imagery and Photography</summary>
<br>

- Downloads: https://unsplash.com/
- https://www.pexels.com/
- https://icons8.com/

</details>
<details>
<summary>Illustration</summary>
<br>

- https://icons8.com/vector-creator
- https://icons8.com/illustrations
- https://www.drawkit.io/
- https://undraw.co/

</details>
<details>
<summary>Design inspiration</summary>
<br>

- https://www.awwwards.com/
- https://httpster.net/2020/aug/
- http://mindsparklemag.com/
- https://medium.muz.li/
- https://dribbble.com/
- https://www.behance.net/
- https://www.invisionapp.com/talks - Talks and interviews about UX and Design.

</details>
<details>
<summary>Free Courses</summary>
<br>

- [Hack Design](https://hackdesign.org/) Free design lessons by designers.
- [Design Lab](http://trydesignlab.com/) Design course with mentorship and projects.

</details>
<details>
<summary>Figma</summary>
<br>

Web based tool for interface design, collaborative, add plugins from community (free, up to 2 editors and 3 projects)

Video explanation of Figma features on their official [YouTube channel](https://www.youtube.com/playlist?list=PLXDU_eVOJTx6zk5MDarIs0asNoZqlRG23&mkt_tok=eyJpIjoiWXpJd09HRmhOelkzWW1aaCIsInQiOiJoRVRDT05JVSsrNzRzTmtBcUdtcDhVYVNsXC95Z2Vwbm92bzVWeGlGSXlnNVJ0REdad21kR05oNHhOZldOUmtscTJLSlwvWmE1ZFZOV0J4bjFQeGliT0h6cmRybTFFdzBHMTZaOHhTbVhha0tCWlZXbmdYTUE1Mk1pczJuRisxeFZMIn0%3D).

- [Build reusable components](https://www.youtube.com/watch?v=k8y9SRPB78Q&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=4)
- [Create reusable color styles](https://www.youtube.com/watch?v=d01Ql9ZtVnk&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=5)
- [Create a shareable team library](https://www.youtube.com/watch?v=79T8Q6OBmRk&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=6)
- [Collaborate in real-time with multiplayer](https://www.youtube.com/watch?v=Zj163lgt_kI&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=7)
- [Build and present interactive prototypes](https://www.youtube.com/watch?v=X5qiBwqptek&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=8)
- [Handoff seamlessly to developers](https://www.youtube.com/watch?v=B242nuM3y2s&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=9)
- [Explore Design Features in Figma](https://www.youtube.com/playlist?list=PLXDU_eVOJTx6zk5MDarIs0asNoZqlRG23&mkt_tok=eyJpIjoiWXpJd09HRmhOelkzWW1aaCIsInQiOiJoRVRDT05JVSsrNzRzTmtBcUdtcDhVYVNsXC95Z2Vwbm92bzVWeGlGSXlnNVJ0REdad21kR05oNHhOZldOUmtscTJLSlwvWmE1ZFZOV0J4bjFQeGliT0h6cmRybTFFdzBHMTZaOHhTbVhha0tCWlZXbmdYTUE1Mk1pczJuRisxeFZMIn0%3D)

</details>
<details>
<summary>UI Kits</summary>
<br>

- https://www.figma.com/templates/
- https://www.uistore.design/types/figma/
- https://www.figmafreebies.com/
- https://www.figmafinder.com/
- [Spell checker for Figma](https://www.figma.com/community/plugin/754026612866636376/SPELLL---Spell-Checking-for-Figma)
- [Accessibility checker for Figma](https://www.figma.com/community/plugin/732603254453395948/Stark)

</details>
<details>
<summary>More Softwares</summary>
<br>

- **Adobe XD**: Interface design and prototyping tool, shared docs, 2GB cloud storage ([free, up to 2 editors and 1 shared document](https://www.adobe.com/be_en/products/xd.html))
- **Sketch**: Interface design / UX and prototyping tool, collaborative ([paid, 30 days trial](https://www.sketch.com/))
- **MindMeister**: Flowcharts and mind maps ([free, up to 3 maps](https://www.mindmeister.com/))
- **Draw.io**: Flowcharts ([paid, 30 days trial](https://drawio-app.com/))

</details>
<details>
<summary>Books</summary>
<br>

- [Don't Make Me Think](https://www.bol.com/nl/p/don-t-make-me-think-revisited/9200000018192369/?bltgh=mLaCpZW-IMbD3dNO48xFIA.1_4.5.ProductImage), by Steve Krug [Suggested study]
- [The User Experience Team of One](https://www.bol.com/nl/p/the-user-experience-team-of-one/9200000082272796/?bltgh=tY-6frkLAyHyaaL6EtNEPQ.1_4.5.ProductImage): A Research and Design Survival Guide, by Leah Buley
- Information Architecture for the World Wide Web, by Louis Rosenfeld and Peter Morville
- [Universal Principles of Design](https://www.bol.com/nl/p/universal-principles-of-design/1001004007106781/?bltgh=mm-7k83-XaFdUXIrXSJObA.1_4.6.ProductImage), by William Lidwell, Kritina Holden, and Jill Butler
- [Information Architecture for the World Wide Web](https://www.bol.com/nl/p/information-architecture-4e/9200000037168400/?bltg=itm_event%3Dclick%26mmt_id%3DX3GnoJ7%40oK68MSh3gAkpbQAAB7Y%26slt_type%3Drecommendations%26pg_nm%3Dpdp%26slt_id%3Dprd_reco%26slt_nm%3Dproduct_recommendations%26slt_pos%3DC1%26slt_owner%3Dccs%26itm_type%3Dproduct%26itm_lp%3D1%26itm_id%3D9200000037168400&bltgh=vKsCEcB7ild3J74TfKNNfQ.1_8_9.10.ProductImage), by Louis Rosenfeld and Peter Morville
- [Atomic Design](https://bradfrost.com/blog/post/atomic-web-design/), by Brad Frost
- [Design Systems](https://www.bol.com/nl/p/design-systems/9200000088832671/) by Alla Kholmatova
- HTML&CSS design and build websites - Jon Duckett ([Free PDF](https://wtf.tw/ref/duckett.pdf)) ([Official website](http://www.htmlandcssbook.com/))
- [Free Online book on Design Engineering](https://www.designbetter.co/design-engineering-handbook)

</details>

### Open Source Software

<details>
<summary>What is Open Source Software?</summary>
<br>

- [Mozilla](https://www.youtube.com/watch?v=7c0IrsDsNaw)
- [Brian Daigle](https://www.youtube.com/watch?v=1ehpgbb3XD0)
  codes of conduct and github walk-through: https://www.youtube.com/watch?v=c6b6B9oN4Vg
- [Explained with Legos](https://www.youtube.com/watch?v=a8fHgx9mE5U)
- [And with recipes](https://www.youtube.com/watch?v=9ShgYrBkTRs)
- [Open Source vs. Closed Source](https://www.youtube.com/watch?v=2q91vTvc7YE)
- [Free/Libre vs. Open Source](https://www.youtube.com/watch?v=Ag1AKIl_2GM) (think "free speech", not "free food")

To learn more about all things Open, check out the [Open Knowledge Foundation](https://okfn.org) and [Open Knowledge Belgium](https://openknowledge.be).

</details>
<details>
<summary>Open Source Licenses</summary>
<br>

The license attached to an Open Source project is not just a detail! Check out these links to learn more about the many licenses available:

- [opensource.org](https://opensource.org/licenses)
- [choosealicense.com](https://choosealicense.com/)
- [techsoup](https://www.techsoup.org/support/articles-and-how-tos/making-sense-of-software-licensing)
- [infoworld](https://www.infoworld.com/article/2839560/sticking-a-license-on-everything.html)
- copyleft: [what is this?](https://www.youtube.com/watch?v=6Xky8HTqaZo), [copyleft.org](https://copyleft.org/)
- :) [ErikMcClure/bad-licenses](https://github.com/ErikMcClure/bad-licenses)

</details>
<details>
<summary>Codes of Conduct</summary>
<br>

The Code of Conduct in an Open Source project describes how contributors should treat each other. Open Source projects are about sharing and welcoming:

- [Contributor Covenant](https://www.contributor-covenant.org/)
- [opensource.guide](https://opensource.guide/code-of-conduct/)
- [opensourcedesign.net](https://opensourcedesign.net/code-of-conduct/)

</details>
<details>
<summary>Contributor Guidelines</summary>
<br>

Contributor Guidelines are important to standardize coding practices and workflows for an Open Source project. You could think of it as describing how the code should be treated:

- [mozillascience](https://mozillascience.github.io/working-open-workshop/contributing/)
- [docs.github.com](https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)
- Templates
  - [briandk](https://gist.github.com/briandk/3d2e8b3ec8daf5a27a62)
  - [opensource.com](https://opensource.com/life/16/3/contributor-guidelines-template-and-tips)
- Examples
  - [opensource.guide](https://github.com/github/opensource.guide/blob/main/CONTRIBUTING.md)
  - [github/docs](https://github.com/github/docs/blob/main/CONTRIBUTING.md)
  - [microsoft/vscode](https://github.com/microsoft/vscode/blob/main/CONTRIBUTING.md)
  - [atom/atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)
  - [voxmedia](https://github.com/voxmedia/open-source-contribution-guidelines)

</details>
<details>
<summary>How to Contribute</summary>
<br>

- [opensource.guide](https://opensource.guide/)
- [freecodecamp](https://github.com/FreeCodeCamp/how-to-contribute-to-open-source)
- [contribution-guide.org](https://www.contribution-guide.org/)
- [redhat](https://www.redhat.com/en/resources/open-source-participation-guidelines-overview)
- [better-programming](https://medium.com/better-programming/4-effortless-steps-for-contributing-to-open-source-projects-35000599367b)
- Small contributions matter!
  - [Why the GitHub metric monoculture?](https://medium.com/@leskis/why-the-github-metric-monoculture-d179a2f1d130)
  - [pybot](https://github.com/lpmi-13/pypobot)

and finally ...

- [Contribute to this Project!](https://github.com/Syknapse/Contribute-To-This-Project)

</details>
<details>
<summary>Open Source Libraries</summary>
<br>

Open Source Libraries are code other people wrote that you can use in your project.

The libraries you will be exploring in this module are CSS Frameworks. These are libraries of CSS classes that you can use in your websites to design and develop more efficiently. You don't need to write the CSS, just use it!

- How to choose a library for your project:
  - [freecodecamp](https://www.freecodecamp.org/news/how-to-choose-between-open-source-libraries-using-popularity-c71677785542/)
  - [open-source.blogspot.com](https://open-source.blogspot.com/)

Now it's your turn. Look through these CSS Framework and pick the best one to use for your home page:

- [awesome-css-frameworks](https://github.com/troxler/awesome-css-frameworks)

</details>
<br>

</details>
<br>

[TOP](#ux-ui-design)

Week X

- [x] started the exercises
- [ ] [project issue](your-link-here)

#### What went less well?
the interviews and getting the needs. I think we both have no idea what it should look like.

### Before Class

- [x] [Design is future](https://www.youtube.com/watch?v=zodT9bCdIiI) - a film that includes main insights about the key role of design while explaining how it helps professionals, businesses and society to be more innovative and sustainable
- [x] [User Experience](https://youtu.be/whtBPzY4K-k) from one of the world leaders of UX Jared Spool. Covers many topics in this hour video interview
- [x] [empathyprompts.net](https://empathyprompts.net/)
- [x] [Design Thinking Process](https://www.youtube.com/watch?v=_r0VX-aU_T8)

#### What went well?
more clear homework for me
#### What went less well?
communication within group
#### Lessons Learned
If stg is late I should check immediately otherwise it will become a delay later
### Sunday Prep Work

- [x] Create a Figma account: www.figma.com
  You need a verified Education Figma account before joining the course!
  Create a Figma account with your email address
  Add your email address on your Slack class channel, we will collect it and invite you to the HYF Education account.
  Open the email sent from Figma to verify your Figma Education account.
  Login into Figma before the course starts.
- [x] Watch the following tutorials:
  - [x] [What's Figma?](https://www.youtube.com/watch?v=Cx2dkpBxst8&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4)
  - [x] [Setup account, teams, projects, and files](https://www.youtube.com/watch?v=hrHL2VLMl7g&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=2)
  - [x] [Get a tour of the Editor](https://www.youtube.com/watch?v=DSrbwCrEIII&list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&index=3)

**Comment by colevandersWands** [comment]
Morning @erkamguresen , could you fill in the questions for this week's check-in? I'm curious to hear how this week's project is coming along

**Comment by colevandersWands** [comment]
Sorry for the late check @erkamguresen: `the interviews and getting the needs. I think we both have no idea what it should look like.` 

@ZM102  just got in touch with me on Slack, she has a better idea how the interviews work.  This is also a great question to ask in review tonight with your coaches

**Comment by colevandersWands** [comment]
> If stg is late I should check immediately otherwise it will become a delay later

Wise words
