### ISSUE TITLE
Selim: UX/UI - Rebuilding My Portfolio Homepage 

### ISSUE THREAD

**Issue by selimensar** [HackYourFutureBelgium/class-13-14#170]
### My Portfolio Home Page
- [repo](https://github.com/selimensar/selimensar.github.io)
  - with your partner:
  - [x] README
  - on your own:
  - [x] License
  - [x] Contributor Guidelines
  - [x] Code of Conduct
- [ ] [live demo](https://selimensar.github.io)
- [/planning](https://github.com/selimensar/selimensar.github.io/tree/master/Planning)
  - with your project partner:
  - [x] interview (your completed interview template)
  - [ ] backlog (developed with your partner based on the interview)
  - [ ] wireframe (design your site's outline together)
  - on your own:
  - [x] schedule (like communication plan, but for yourself)
  - [ ] constraints (include the CSS framework you chose and why)
  - [ ] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/selimensar/selimensar.github.io/projects/1)

## My Contributions

- Home Pages:
  - [x] [Chyngyz](link_to_your_contribution)
  
 - CSS Framework Name:
  - [ ] [describe contribution](link_to_your_contribution)

**Comment by colevandersWands** [comment]
Morning @selimensar , could you fill in the check-in questions for this week?  I'm curious to hear how you're liking the design module

**Comment by colevandersWands** [comment]
@selimensar , could you separate this into two issues please?  One for keeping track of your study using the Check-In template, and another with your project checklist using the Project template.  Then only the project issue needs to be on the project board

**Comment by selimensar** [comment]
@colevandersWands thanks for notifying me.  I separated it into two issues just like you said: https://github.com/HackYourFutureBelgium/class-13-14/issues/179

And I'm aware of that I need to forward inside fastly 🏃
