### ISSUE TITLE
rago89: Debugging, 4 weeks

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-13-14#212]
> [module repository](https://github.com/HackYourFutureBelgium/debugging)

## Study Plan
<details>
<summary>expand/collapse</summary>
<br>

### Debugging Tools
<details>
<summary>expand/collapse</summary>
<br>

- [x]  [Errors & Debugging](https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/index.html)
- [x]  [Developer Console](https://javascript.info/devtools)
- [x]  [Debugging in Chrome](https://javascript.info/debugging-chrome)
- [x]  [definitive: 2021](https://dev.to/atapas/the-definitive-guide-to-javascript-debugging-2021-edition-116n)
- [x]  [breakpoints](https://developers.google.com/web/tools/chrome-devtools/javascript/reference)
- [x] [Debugging in FireFox](https://developer.mozilla.org/en-US/docs/Tools/Debugger)
- [x]  [pythontutor.com](http://pythontutor.com/) -> [JS Tutor](http://pythontutor.com/javascript.html)
- [x] [VSCode](https://code.visualstudio.com/Docs/editor/debugging)
</details>

### Regular Expressions
<details>
<summary>expand/collapse</summary>
<br>

- [x]   [regex.guide](https://regex.guide/): learn to build regular expressions one question at a time
- [x]    [regexer.com](https://regexr.com/): realtime regex with a visual breakdown of your regular expression
- [ ]    [Regex Crossword](https://regexcrossword.com/): games to learn regular expressions References
- [x]    [The Coding Train](https://shiffman.net/a2z/regex/)
- [x]    [javascript.info](https://javascript.info/regular-expressions)
- [x]    [FreeCodeCamp](https://www.youtube.com/watch?v=909NfO1St0A)
- [x]    [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)
</details>

### Exercises 
<details>
<summary>expand/collapse</summary>
<br>

- [x]  🥚 **[./stepping-through](./stepping-through)
- [x] 🥚 **[./describing-errors](./describing-errors)
- [x]  🥚 **[./isolate](./isolate)
- [x] 🥚 **[./interact](./interact)
- [ ] -🥚 **[./hoisting](./hoisting)
</details>
</details>

### Week 1
<details>
<summary>expand/collapse</summary>
<br>

- [x] started the exercises

#### I Need Help With:
for the moment no need
#### What went well?
Practice, lots of exercises to make
#### What went less well?
Problems with the laptop  now everything it's working well again 
#### Lessons Learned
</details>

### Week 2
<details>
<summary>expand/collapse</summary>
<br>

- [x] started the exercises

#### I Need Help With:
Nothing yet
#### What went well?
Understanding easier the concepts
#### What went less well?
Study with kids around the house is not easy
#### Lessons Learned
Too many content to keep in the head, building a summary guide that is easily accessible when it comes to needing some information
### Sunday Prep Work
hope to be ready at Friday

**Comment by colevandersWands** [comment]
> Too many content to keep in the head, building a summary guide that is easily accessible when it comes to needing some information

@rago89 , I'd be curious to see your guide. How have you been using it so far?

PS. can you leave your check-in as a comment next week like in #217?  that's making it easier to review and will keep your study guide in the description cleaner

**Comment by rago89** [comment]
Is more like a resume, I have started with arrays is not all the content but I'll be adding new things when I see it, now I'm with functions is to much info to Master, and next week I'll be doing objects.  https://github.com/rago89/my-study-guide

**Comment by rago89** [comment]
> > Too many content to keep in the head, building a summary guide that is easily accessible when it comes to needing some information
> 
> @rago89 , I'd be curious to see your guide. How have you been using it so far?
> 
> PS. can you leave your check-in as a comment next week like in #217?  that's making it easier to review and will keep your study guide in the description cleaner

Is more like a resume, I have started with arrays is not all the content but I'll be adding new things when I see it, now I'm with functions is to much info to Master, and next week I'll be doing objects.  https://github.com/rago89/my-study-guide

**Comment by rago89** [comment]
if you see if there is ani method that is helpful that is not there can you let me know, I use the  'JavaScript: The Definitive Guide' as a guide

**Comment by rago89** [comment]
### Week 3

#### I Need Help With:
Nothing yet
#### What went well?
Finally, I understood well II think the scope of `this` in regular functions and arrow functions, lexical scope, closure, methods like call, apply, and joint 
#### What went less well?
Learning functions takes more time than I thought, tomorrow I will be continuing, with the next steps of debugging 
#### Lessons Learned
Knowing where to stop to avoid drowning
### Sunday Prep Work

**Comment by colevandersWands** [comment]
> Knowing where to stop to avoid drowning

: ) looks like you figured it out the hard way this week. functions are a fun and strange thing in JS

**Comment by rago89** [comment]
> > Knowing where to stop to avoid drowning
> 
> : ) looks like you figured it out the hard way this week. functions are a fun and strange thing in JS

Still searching the easy way but always return undefined

**Comment by rago89** [comment]
Week 4
I Need Help With:
Nothing yet

What went well?
Objects, still also still study more getters and setters, get the idea but I have to study more

What went less well?
Health issues, very tired  

Lessons Learned
Avoid rush 

Sunday Prep Work
tomorrow I'll be done
