### ISSUE TITLE
Behavior, Strategy, Implementation, week 3, Sunday Roll Call

### ISSUE THREAD

**Issue by Lizhen2910** [HackYourFutureBelgium/class-13-14#258]
Leave a comment with these two things:

1. A summary of your week using only emojis
2. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by Fatihayoz** [comment]
:climbing_man: :volcano:

**Comment by OksanaShulha** [comment]
first step :cloud: next step :cloud: :cloud: keep calm :zap: :cyclone: :umbrella: keep doing what you do :partly_sunny: don't stop :partly_sunny: don't! :partly_sunny: ......  :sunny::sunny::sunny::sunny::sunny::sunny::sunny::sunny::sunny:

**Comment by IrinaSing** [comment]
👧 ⌨️ VS 🤖 💻

**Comment by rago89** [comment]
:smiley: :zany_face: :mask: :mechanical_arm:

**Comment by sabanyelkenci** [comment]
:+1:

**Comment by gustavoaespitia** [comment]
🤖 
it is coming

**Comment by alinamarasca** [comment]
:fish: :boom: :fish_cake: :recycle: :fish: :explosion: :fish_cake: :recycle: :octopus: :boom: :octopus: :octopus: :octopus:

**Comment by emelysalmeron** [comment]
💻 😟 🔢 🏃🏼‍♀️ 🐌

**Comment by sheybusta** [comment]
:turtle::turtle::turtle:

**Comment by mayuri2510** [comment]
1 💻 ⏳ 😞 
2 couldn't manage to spend enough time on study because of personal work.

**Comment by zehrayelkenci** [comment]
:+1:  :slightly_smiling_face: :wink:

**Comment by Lizhen2910** [comment]
I see some of you are "man or women of few emojis". An image is worth a thousand words, an emoji is worth a dozen words... Have a great week!
