### ISSUE TITLE
Alina Marasca: individual project

### ISSUE THREAD

**Issue by alinamarasca** [HackYourFutureBelgium/class-13-14#26]
A home page for myself using HTML & CSS.

- [x] [repo](https://github.com/alinamarasca/alinamarasca.github.io)
- [x] a great README file
- [x] [live demo](https://alinamarasca.github.io/)
- [x] [many small, well-named commits](https://github.com/alinamarasca/alinamarasca.github.io/commits)

**Comment by colevandersWands** [comment]
Well done @alinamarasca!  Your site looks good, the code is tidy, and your commit messages are helpful. 

There was a mistake in your README, the link to hackyourfuture.be was broken.  I've sent you a PR for that.
