### ISSUE TITLE
Furkan KILIC:  Individual Project 

### ISSUE THREAD

**Issue by kilicf** [HackYourFutureBelgium/class-13-14#28]
- [x] [Repo](https://github.com/kilicf/kilicf.github.io)

- [x] A great README file

- [x] [Live demo](https://kilicf.github.io/)

- [x] [Many small, well-named commits](https://github.com/kilicf/kilicf.github.io/commits/main)

**Comment by kilicf** [comment]
- [ ] Preview prepared until preparations are completed.

[Site](https://kilicf.github.io/)

**Comment by colevandersWands** [comment]
Good morning @kilicf, could you add links to your repo and demo in your issue?  Mention me `@colevanderswands` once you have the links ready and I can take a look at your project

**Comment by kilicf** [comment]
Hi @colevandersWands , I added the links. Thank you.

**Comment by Mika215** [comment]
Trying to create my own individual project.

**Comment by colevandersWands** [comment]
Looks good @kilicf , plenty of well named commits and a pretty site 🚀.   

the HTML in your about file could have more consistent indentation but that's something you can work on for the next projects.  Using the `prettier` extension in VSCode will also help by formatting your code each time you save.

**Comment by kilicf** [comment]
Thank you  @colevandersWands  :v:
