### ISSUE TITLE
Single-Page-Apps, week 1, Sunday Roll Call

### ISSUE THREAD

**Issue by iLienstAr** [HackYourFutureBelgium/class-13-14#306]
Leave a comment with these two things:

1. A summary of your week using only emojis
2. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by IrinaSing** [comment]
:woman::scream::arrow_right::older_woman:

**Comment by erkamguresen** [comment]
📚 💻🤓🤯

**Comment by OksanaShulha** [comment]
:climbing_woman::climbing_woman::climbing_woman:

**Comment by sabanyelkenci** [comment]
:house: :arrow_right: :house: :weary:

**Comment by zehrayelkenci** [comment]
:expressionless:  :roll_eyes:  :pensive:

**Comment by alinamarasca** [comment]
1. :student: :man_student: : :champagne: :sunglasses:
2. big thanks to Evan for having our backs!

**Comment by mayuri2510** [comment]
💻 📚 👍

**Comment by Fatihayoz** [comment]
:computer: :books:

**Comment by sheybusta** [comment]
:thumbsup: :computer:
