### ISSUE TITLE
Fatih Ayöz: Adventures of a Newbie in the Jungle of 01010111-01100101-01100010

### ISSUE THREAD

**Issue by Fatihayoz** [HackYourFutureBelgium/class-13-14#31]
- [x] [repo](https://github.com/Fatihayoz/Fatihayoz.github.io)
- [x] a great README file
- [x] [live demo](https://fatihayoz.github.io/)
- [x] [many small, well-named commits](https://github.com/Fatihayoz/Fatihayoz.github.io/commits)

**Comment by Fatihayoz** [comment]
First steps of the individual project

**Comment by Fatihayoz** [comment]
Updated

**Comment by colevandersWands** [comment]
Well done @Fatihayoz!  This is a full project: README, helpful commit messages, tidy code, and a live demo.  Keep it up 💪
