### ISSUE TITLE
rago89: Asynchronous Programming, 3w

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-13-14#318]
> [module repository](https://github.com/rago89/asynchronous-programming)

Individual project 

## Study Plan
<details>
<summary>expand/collapse</summary>

### The Event Loop

- [x] - [Coding Nomad](https://www.youtube.com/watch?v=5YcMKYTZZvk) - short clear example
- [x] - [Java Brains](https://www.youtube.com/watch?v=EI7sN1dDwcY) - restaurant analogy
- [x] - [Loupe](http://latentflip.com/loupe/) (+10)
- [x] - [In the Loop](https://www.youtube.com/watch?v=cCOL7MC4Pl0) (+10)
- [x] - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop)
- [x] - [flavicops](https://flaviocopes.com/javascript-event-loop/)
- [x] - [javascript.info/settimeout-setinterval](https://javascript.info/settimeout-setinterval)
- [x] - [https://javascript.info/event-loop](https://javascript.info/event-loop)
- [ ] - [Use case for using setTimeout(0)](https://javascript.info/event-loop#use-case-3-doing-something-after-the-event)
- [ ] - [Beau from FCC](https://www.youtube.com/watch?v=kOcFZV3c75I) (timeouts & intervals)

### Callbacks, Promises, Async

- References

- [x]   - [Coding Train](https://www.youtube.com/watch?v=QO4NXhWo_NM&list=PLRqwX-V7Uu6bKLPQvPRNNE65kBL62mVfx)
- [ ]   - [Dev Ed](https://www.youtube.com/watch?v=_8gHHBlbziw)
- [x]   - [Traversy](https://www.youtube.com/watch?v=PoRJizFvM7s)
- [x]   - [javascript.info](https://javascript.info/async)

</details>

Week I

- [x] [repo](https://github.com/rago89/stopWatch) (with a complete README)
- [x] [live demo](https://rago89.github.io/stopWatch/)
  - with one page for each version
  - each version can be identical for the user, but have different code
- [/planning](https://github.com/_/_/tree/master/planning)
  - [ ] constraints
  - [ ] backlog
  - [ ] wireframe
  - [ ] development strategy
  - [ ] retrospective

### Sunday Prep Work

---- END CHECK-IN TEMPLATE ----

**Comment by rago89** [comment]
### Check-In

#### I Need Help With:
My clock Page, I have  created the code with callbacks, but I don't think that's the correct approach, I need feedback 

#### What went well?
Use set interval somehow

#### What went less well?

#### Lessons Learned

### Sunday Prep Work
Tomorrow I'll finish with promises and async, hope to be ready by Friday

**Comment by colevandersWands** [comment]
@rago89 , can you put your project issue on the board?  mention/assign me in it and i'll take a look

**Comment by rago89** [comment]
Thanks, Evan, I made only callbacks, I think is the hardest one, once you take a look I will create the folders to  refactor with promises and async, I'm also thinking to create 3 buttons to switch between implementations in the same page.
