### ISSUE TITLE
rago89: incremental-development, w1,w2, w3

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-13-14#82]
## Week I

> [module repository](https://github.com/rago89/incremental-development)

### Suggested Study

 - **_Incremental Development_**
<details>
<summary>expand/collapse</summary>

- [x] - [What is this?](https://www.youtube.com/watch?v=GzzkpAOxHXs)
- [x] - [Agile Development by Cartoon](https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS)
- [x] - [Atlassian](https://www.atlassian.com/team-playbook/plays), [Team Playbook](https://www.atlassian.com/team-playbook/plays)
- [x] - [Splitting User Stories](https://www.youtube.com/watch?v=EDT0HMtDwYI)
- [x] - [Three key parts](https://www.youtube.com/watch?v=ctFzjMygaRo)
- [x] - [`development-strategy.md` files](https://home.hackyourfuture.be/students/development-strategy)
- [x] - [example development strategies](./development-strategies)
- [x] - [example group repo](https://github.com/HackYourFutureBelgium/team-branchies)
- [x] - All About Trees: [in steps](./all-about-trees-stepped), [as a repo](https://github.com/hackyourfuturebelgium/built-with-

</details>

 - **_Writing READMEs_**
<details>
<summary>expand/collapse</summary>

- [x] - [makeareadme.com](https://www.makeareadme.com/)
- [x] - [bulldogjob](https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project)
- [x] - [meakaakka](https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3)

</details>

-  **_User Stories_**

<details>
<summary>expand/collapse</summary>

- [x] - [User Stories](https://www.youtube.com/watch?v=apOvF9NVguA)
- Acceptance Criteria
- [x]   - [Yodiz](https://www.yodiz.com/blog/user-stories-acceptance-definition-and-criteria-in-agile-methodologies/)
- [x]   - [Zepel](https://zepel.io/agile/acceptance-criteria-for-user-stories/)
- [x]   - [Ruby Garage](https://rubygarage.org/blog/clear-acceptance-criteria-and-why-its-important)
- [x]   - [The Infinity Project](https://www.youtube.com/watch?v=KYS0ptJ4JWc)
- Setting Priorities
- [x]   - [Many Strategies](https://zapier.com/blog/how-to-prioritize)
- [ ]   - The Priority Quadrant
- [ ]     - [The Quadrant](https://www.youtube.com/watch?v=NGvsxPOmWuw)
- [ ]     - [Problems with this method](https://www.linkedin.com/pulse/why-prioritization-impacteffort-doesnt-work-itamar-gilad)
 - Other Perspectives
- [ ]     - [Alex Ponomarev](https://medium.com/swlh/prioritizing-user-stories-in-agile-projects-d1dd8dd79165)
- [ ]     - [Michael Lant](https://michaellant.com/2010/05/21/how-to-easily-prioritize-your-agile-stories/)

</details>

### Group Issue
    
- [x] [Group issue](https://github.com/HackYourFutureBelgium/class-13-14/issues/79)

#### I Need Help With:
 For the instance nothing waiting for the fun in debugging 
#### What went well?
The team is getting well the concepts and we are on a good way 
#### What went less well?
Missing a lot of teammates
#### Lessons Learned
For much that we can know there is always a lot to learn

### Suggested Study

 - **_DevTools and the DOM_**
<details>
<summary>expand/collapse</summary>

- [x]  [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
- [ ]  [inspecting-the-dom](https://hackyourfuturebelgium.github.io/inspecting-the-dom/)
- [x]  [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)

</details>

### Suggested Study

 - **_HTML & CSS_**
<details>
<summary>expand/collapse</summary>

- [x]  FCC, Responsive Web Design: [exercises](https://www.freecodecamp.org/learn), [video](https://www.youtube.com/watch?v=srvUrASNj0s)
- [x]  [mmtuts: HTML & CSS](https://www.youtube.com/watch?v=TKYsuU86-DQ&list=PL0eyrZgxdwhwNC5ppZo_dYGVjerQY3xYU)
- [x]  [CSS Games](https://study.hackyourfuture.be/html-css/css#games-to-learn-css)
- [x] :egg: [html-css-git-exercises](https://github.com/hackyourfuturebelgium/html-css-git-exercises)
- [x] :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [x] :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

</details>

### Group Issue
    
- [x] [Group issue](https://github.com/inggritenovaleta/hackyourfuture-g4)

### Check-In
Everything so far good, the team is working very well almost everything set up for start coding 

#### I Need Help With:
Nothing until now
#### What went well?
The capacity of my teammates to develop planning project 
#### What went less well?
That the other teammates couldn't join 
#### Lessons Learned
The importance of creating a culture of sharing 

### Group Issue
    
- [x] [Group issue](https://github.com/inggritenovaleta/hackyourfuture-g4)
---

- [x] Sunday Prep

- [x] Sunday Class

#### I Need Help With:
Nothing for the instance
#### What went well?
Lots of interaction on gitHub, good team communication, importance of git, a lot of improvement on git.
#### What went less well?
Git workflow as a group.
#### Lessons Learned
Prioritize, set a good and real week's plan on the issue

**Comment by colevandersWands** [comment]
👋  @rago89 , the [check-in labeling](https://home.hackyourfuture.be/students/hyf-workflows/wednesday-check-in) is a little different for 13-14. hopefully a little simpler.

`individual` is now just for projects, the checkin will just have `check-in` and `week-x`.  Trying to keep the number of labels on each issue down

**Comment by colevandersWands** [comment]
Thanks again for helping out last week and yesterday

**Comment by colevandersWands** [comment]
> For the instance nothing waiting for the fun in debugging

🐜

**Comment by colevandersWands** [comment]
> The importance of creating a culture of sharing

@rago89 , any tips for this? what's worked well for your group so far?

**Comment by rago89** [comment]
I think that switching roles, was good.

**Comment by snicoll** [comment]
Very good point @rago89. Worth sharing during class next Sunday.

**Comment by colevandersWands** [comment]
@rago89 , `Git workflow as a group.` Was it not clear, or just difficult?  Let me know if there's anything in the instructions we can clarify

**Comment by rago89** [comment]
The recording of Sunday class is a very good material, and also in suggest to study, I think that during this week is going to be better, is a matter of practice on the right way.
