### ISSUE TITLE
Alina: incremental-development, week 1

### ISSUE THREAD

**Issue by alinamarasca** [HackYourFutureBelgium/class-13-14#84]
> [module repository](https://github.com/alinamarasca/incremental-development)

### Incremental Development
- [x] [What is this?](https://www.youtube.com/watch?v=GzzkpAOxHXs)
- [x] [Agile Development by Cartoon](https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS)
- [x] [Atlassian](https://www.atlassian.com/team-playbook/plays), [Team Playbook](https://www.atlassian.com/team-playbook/plays)
-  [x] [Splitting User Stories](https://www.youtube.com/watch?v=EDT0HMtDwYI)
-  [x] [Three key parts](https://www.youtube.com/watch?v=ctFzjMygaRo)
-  [x] [`development-strategy.md` files](https://home.hackyourfuture.be/students/development-strategy)
- [x]  [example development strategies](./development-strategies)
- [x]  [example group repo](https://github.com/HackYourFutureBelgium/team-branchies)
-  [x] All About Trees: [in steps](./all-about-trees-stepped), [as a repo](https://github.com/hackyourfuturebelgium/built-with-branches)
---

 - [x] ### Command Line Interface

- [Jesse Showalter](https://www.youtube.com/watch?v=5XgBd6rjuDQ)
- CLI games:
  - [bashcrawl](https://gitlab.com/slackermedia/bashcrawl/) - clone & play
  - [Terminus](https://web.mit.edu/mprat/Public/web/Terminus/Web/main.html) - online
  - [iTerm](https://sr6033.github.io/lterm/) - online
- [A huge cheat sheet](https://gist.github.com/LeCoupa/122b12050f5fb267e75f)
- [study.hyf.be](https://study.hackyourfuture.be/cli)

- [x] ### Writing READMEs

- [makeareadme.com](https://www.makeareadme.com/)
- [bulldogjob](https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project)
- [meakaakka](https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3)

- [x] ### DevTools and the DOM

- [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
- [inspecting-the-dom](https://hackyourfuturebelgium.github.io/inspecting-the-dom/)
- [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)

### HTML & CSS

- [ ]  FCC, Responsive Web Design: [exercises](https://www.freecodecamp.org/learn), [video](https://www.youtube.com/watch?v=srvUrASNj0s)
-  [x] [mmtuts: HTML & CSS](https://www.youtube.com/watch?v=TKYsuU86-DQ&list=PL0eyrZgxdwhwNC5ppZo_dYGVjerQY3xYU)
- [ ] [CSS Games](https://study.hackyourfuture.be/html-css/css#games-to-learn-css)
- [ ]  :egg: [html-css-git-exercises](https://github.com/hackyourfuturebelgium/html-css-git-exercises)- [ ]  :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [x]  :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Collaborating on GitHub

-  [x] [Adding collaborators to a repository](https://www.youtube.com/watch?v=p49LRx3hYI8)
-  [ ] [about code reviews](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews)
-  [x] [requesting a code review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)
-  [ ] [Git Workflow for 2](https://github.com/hackyourfuturebelgium/git-workflow-workshop-for-two)
-  [x] [Pull Requests](https://www.youtube.com/watch?v=2M16faxEQsg)
-  [ ][Git & GitHub for Poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
-  [ ] The Net Ninja: [11](https://www.youtube.com/watch?v=MnUd31TvBoU&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=11)
-  [ ] linking PRs to Issues: [reference 1](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), [reference 2](https://help.github.com/articles/autolinked-references-and-urls/)
-  [ ] [closing Issues using keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)

### User Stories

- [x] [User Stories](https://www.youtube.com/watch?v=apOvF9NVguA)
- Acceptance Criteria
  - [Yodiz](https://www.yodiz.com/blog/user-stories-acceptance-definition-and-criteria-in-agile-methodologies/)
  - [Zepel](https://zepel.io/agile/acceptance-criteria-for-user-stories/)
  - [Ruby Garage](https://rubygarage.org/blog/clear-acceptance-criteria-and-why-its-important)
  - [The Infinity Project](https://www.youtube.com/watch?v=KYS0ptJ4JWc)
- [ ] Setting Priorities
  - [Many Strategies](https://zapier.com/blog/how-to-prioritize)
  - The Priority Quadrant
    - [The Quadrant](https://www.youtube.com/watch?v=NGvsxPOmWuw)
    - [Problems with this method](https://www.linkedin.com/pulse/why-prioritization-impacteffort-doesnt-work-itamar-gilad)
  - [ ] Other Perspectives
    - [Alex Ponomarev](https://medium.com/swlh/prioritizing-user-stories-in-agile-projects-d1dd8dd79165)
    - [Michael Lant](https://michaellant.com/2010/05/21/how-to-easily-prioritize-your-agile-stories/)

### Week 1

- [x] started the exercises
- [x] [project issue](https://github.com/HackYourFutureBelgium/class-13-14/issues/83)

### Check-In
Didn't read as much as I wanted to
#### What went well?
* generating ideas
* watching Loruki video by Brad Traversy :smile: 
#### What went less well?
* meetings with all the members of the team is tricky
*  find common sense :sweat_smile: 
#### Lessons Learned
* Name branches by function
* read more
### Week 2

- [x] started the exercises
- [x] [project issue](https://github.com/HackYourFutureBelgium/class-13-14/issues/116)

### Check-In
Felt in love with Agile Development method
#### I Need Help With:
explanation why is development strategy based on user's stories, not on page structure :sweat: 
#### What went well?
* generating ideas
* meeting everyday with most of the group
#### What went less well?
* working on one file with pull requests 
* study/private life balance
#### Lessons Learned
* sum up meeting for those, who was not present
* do more individual study and exercise
### Sunday Prep Work
* retrospective
* questions

**Comment by colevandersWands** [comment]
> meetings with all the members of the team is tricky

the goal of all this planning and issues is that soon you won't need meet as often. once everyone is comfortable coming up with a backlog and setting up a project board you'll be able to do it mostly by slack and PR.  
And once everyone is comfortable with tracking issues on the project board, then you can work when you have time and only meet to review the project.  

but one step at a time.  you're already doing a great job coordinating

**Comment by colevandersWands** [comment]
> explanation why is development strategy based on user's stories, not on page structure 😓

everything is based on the user stories!  The page structure (wireframe) is designed to support the user stories, and development is based on providing one complete user story at a time. 
So in a way development is based on the page structure, but only because the page structure is based on the user stories.

More clear or less clear? 🤷

**Comment by alinamarasca** [comment]
@colevandersWands It's been clear to me for a wile now, but the problem was(or is) to explain it to others.

**Comment by colevandersWands** [comment]
@alinamarasca , could you answer the check-in questions for this week? Curious to hear how it's going for you
