### ISSUE TITLE
Erkam: Incremental Development, 3 weeks

### ISSUE THREAD

**Issue by erkamguresen** [HackYourFutureBelgium/class-13-14#90]
> [module repository](https://github.com/erkamguresen/incremental-development)

### Incremental Development
- [x] [What is this?](https://www.youtube.com/watch?v=GzzkpAOxHXs)
- [x] [Agile Development by Cartoon](https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS)
- [ ] [Atlassian](https://www.atlassian.com/team-playbook/plays), [Team Playbook](https://www.atlassian.com/team-playbook/plays)
-  [x] [Splitting User Stories](https://www.youtube.com/watch?v=EDT0HMtDwYI)
-  [ ] [Three key parts](https://www.youtube.com/watch?v=ctFzjMygaRo)
-  [ ] [`development-strategy.md` files](https://home.hackyourfuture.be/students/development-strategy) **~broken link**
- [ ]  [example development strategies](./development-strategies)
- [ ]  [example group repo](https://github.com/HackYourFutureBelgium/team-branchies)
-  [ ] All About Trees: [in steps](./all-about-trees-stepped), [as a repo](https://github.com/hackyourfuturebelgium/built-with-branches)
---

 - [ ] ### Command Line Interface

- [Jesse Showalter](https://www.youtube.com/watch?v=5XgBd6rjuDQ)
- CLI games:
  - [bashcrawl](https://gitlab.com/slackermedia/bashcrawl/) - clone & play
  - [Terminus](https://web.mit.edu/mprat/Public/web/Terminus/Web/main.html) - online
  - [iTerm](https://sr6033.github.io/lterm/) - online
- [A huge cheat sheet](https://gist.github.com/LeCoupa/122b12050f5fb267e75f)
- [study.hyf.be](https://study.hackyourfuture.be/cli)

- [x] ### Writing READMEs

- [makeareadme.com](https://www.makeareadme.com/)
- [bulldogjob](https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project)
- [meakaakka](https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3)

- [ ] ### DevTools and the DOM

- [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
- [inspecting-the-dom](https://hackyourfuturebelgium.github.io/inspecting-the-dom/)
- [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)

### HTML & CSS

- [ ]  FCC, Responsive Web Design: [exercises](https://www.freecodecamp.org/learn), [video](https://www.youtube.com/watch?v=srvUrASNj0s)
-  [ ] [mmtuts: HTML & CSS](https://www.youtube.com/watch?v=TKYsuU86-DQ&list=PL0eyrZgxdwhwNC5ppZo_dYGVjerQY3xYU)
- [ ] [CSS Games](https://study.hackyourfuture.be/html-css/css#games-to-learn-css)
- [ ]  :egg: [html-css-git-exercises](https://github.com/hackyourfuturebelgium/html-css-git-exercises)- [ ]  :hatching_chick: [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ]  :hatched_chick: [css-exercises](https://github.com/dangodev/css-exercises)

### Collaborating on GitHub

- [Adding collaborators to a repository](https://www.youtube.com/watch?v=p49LRx3hYI8)
- [about code reviews](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews)
- [requesting a code review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)
- [Git Workflow for 2](https://github.com/hackyourfuturebelgium/git-workflow-workshop-for-two)
- [Pull Requests](https://www.youtube.com/watch?v=2M16faxEQsg)
- [Git & GitHub for Poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
- The Net Ninja: [11](https://www.youtube.com/watch?v=MnUd31TvBoU&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=11)
- linking PRs to Issues: [reference 1](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), [reference 2](https://help.github.com/articles/autolinked-references-and-urls/)
- [closing Issues using keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)

### User Stories

- [x] [User Stories](https://www.youtube.com/watch?v=apOvF9NVguA)
- Acceptance Criteria
  - [Yodiz](https://www.yodiz.com/blog/user-stories-acceptance-definition-and-criteria-in-agile-methodologies/)
  - [Zepel](https://zepel.io/agile/acceptance-criteria-for-user-stories/)
  - [Ruby Garage](https://rubygarage.org/blog/clear-acceptance-criteria-and-why-its-important)
  - [The Infinity Project](https://www.youtube.com/watch?v=KYS0ptJ4JWc)
- [ ] Setting Priorities
  - [Many Strategies](https://zapier.com/blog/how-to-prioritize)
  - The Priority Quadrant
    - [The Quadrant](https://www.youtube.com/watch?v=NGvsxPOmWuw)
    - [Problems with this method](https://www.linkedin.com/pulse/why-prioritization-impacteffort-doesnt-work-itamar-gilad)
  - [ ] Other Perspectives
    - [Alex Ponomarev](https://medium.com/swlh/prioritizing-user-stories-in-agile-projects-d1dd8dd79165)
    - [Michael Lant](https://michaellant.com/2010/05/21/how-to-easily-prioritize-your-agile-stories/)

### Week 1

- [x] started the exercises
- [x] [project issue](https://github.com/HackYourFutureBelgium/class-13-14/issues/83)

#### What went well? 

Team work is improving. And we handled the map fear (replica of the HYF map with HTML only)

#### What went well? 

Team work is improving. problem solving and asking for help was much better

**Comment by colevandersWands** [comment]
@erkamguresen  , could you answer in the **Check-In** questions for week 1?  No need for long answers, just enough to let us know how you're doing.  

These check-ins aren't only for coaches, they're also for you and your classmates.  You can read through each other's issues to see who is working on the same things, and to learn from each other's lessons

**Comment by colevandersWands** [comment]
complex documentation: a simple briefing would be good if the principles or methodologies used in the project were explained.

What kind of briefing would be most helpful? More videos? a mid-week call?

It rake a lot of time (still takes) to understand what are we doing, team work with different levels and availabilities.

This is expected, it's not an easy thing to figure out. The goal of these three weeks is that you take the time you need to practice planning and working in groups.
In a regular week as a developer, so much of your time will go to understanding what needs to be done then working in a group with mixed levels. The more practice you have before graduating, the better off you will be in your first post

**Comment by erkamguresen** [comment]
> > complex documentation: a simple briefing would be good if the principles or methodologies used in the project were explained.
> 
> What kind of briefing would be most helpful? More videos? a mid-week call?
I am not sure but get lost too much. At some point you (maybe) already mentioned the things. More videos will help. The point I had difficulty was what are we doing (this is mostly answered already) and why are we doing or what is idea doing this way? 
Thus I think I could prioritize what to study. There a lot of stuff to study but I could not prepare a good study plan to follow.
> 
> > It rake a lot of time (still takes) to understand what are we doing, team work with different levels and availabilities.
> 
> This is expected, it's not an easy thing to figure out. The goal of these three weeks is that you take the time you need to practice planning and working in groups.
> In a regular week as a developer, so much of your time will go to understanding what needs to be done then working in a group with mixed levels. The more practice you have before graduating, the better off you will be in your first post

**Comment by colevandersWands** [comment]
> do it in a sperate file if possible and after decide to use what code in actual file

@erkamguresen, this is nice way to do things. I also like to make a mini-version of every little piece before integrating it into the larger project.

> Thus I think I could prioritize what to study. There a lot of stuff to study but I could not prepare a good study plan to follow.

Are you having a better time prioritizing this week now that the big picture is more clear? Let me know if you have any questions about what to focus on

**Comment by erkamguresen** [comment]
> Are you having a better time prioritizing this week now that the big picture is more clear? Let me know if you have any questions about what to focus on

definitely, as the workflow becomes familiar, the prioritizing becomes easier, and also learning the fundamental things decreases the amount of fundamental questions like 'what are we doing now?' or 'why are we doing this?'

**Comment by colevandersWands** [comment]
>  git rebase done perfectly without any pain.

: )
