### ISSUE TITLE
Reinaldo Perez: Incremental-Development, 3 weeks

### ISSUE THREAD

**Issue by perezrei** [HackYourFutureBelgium/class-13-14#96]
# [module repository](https://github.com/perezrei/incremental-development_)

- [x] Sunday Prep
- [x] Sunday Lesson
- [x] Group Project issue

**Progress**: I have learned the importance of communication with the team. To write a good README file. I have practiced more using git from CLI and VSCode. And finally the objective of this module: do one thing at a time an good before pass to the next step communicating effectively with the rest of the team.

**Blocked**: What are you having trouble understanding? So far I'm not having trouble to understand the instructions once that I find them. Sometimes it's hard for me to look for them though it's just the first week. I understand that is a process.

**Next Steps**: Start coding and finish my part of the home page of the project and collaborate with the rest of the team in anything they need. Finish suggested study.

**Tip(s) of the Week**: Read all the instructions of the module on monday morning is the first thing we must do before starting doing anything else.

### Planning and Collaborating
<details>
<summary>expand/collapse</summary>
<br>

- [x] A repository
- [x]  Planning Documents
- [x]  Issues
- [x]  Labels, milestones and assignees
- [x]  A Project Board
- [x]  Pull Requests + code review

### Incremental Development
<details>
<summary>expand/collapse</summary>
<br>

- [x] [What is this?](https://www.youtube.com/watch?v=GzzkpAOxHXs)
- [x] [Agile Development by Cartoon](https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS)
- [x] [Atlassian](https://www.atlassian.com/team-playbook/plays), [Team Playbook](https://www.atlassian.com/team-playbook/plays)
- [x] [Splitting User Stories](https://www.youtube.com/watch?v=EDT0HMtDwYI)
- [x] [Three key parts](https://www.youtube.com/watch?v=ctFzjMygaRo)

### Git & GitHub
<details>
<summary>expand/collapse</summary>
<br>

- [x] [learngitbranching](https://learngitbranching.js.org/)
- [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
- [x] lab.github.com:
      - [First Day on GitHub](https://lab.github.com/githubtraining/first-day-on-github)
      - [First Week on GitHub](https://lab.github.com/githubtraining/first-week-on-github)
- [x] [The Net Ninja](https://www.youtube.com/watch?v=QV0kVNvkMxc&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=8)
- [ ] [git-it](https://github.com/jlord/git-it-electron/)
- [ ] [Understand how to use Atomic Commits](https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git)

### Command Line Interface
<details>
<summary>expand/collapse</summary>
<br>

- [ ] [Jesse Showalter](https://www.youtube.com/watch?v=5XgBd6rjuDQ)
- [ ] CLI games:
        - [bashcrawl ](https://gitlab.com/slackermedia/bashcrawl/)- clone & play
        - [Terminus ](https://web.mit.edu/mprat/Public/web/Terminus/Web/main.html)- online
        - [iTerm ](https://sr6033.github.io/lterm/)- online
- [ ] [A huge cheat sheet](https://gist.github.com/LeCoupa/122b12050f5fb267e75f)
- [ ] [study.hyf.be](https://study.hackyourfuture.be/cli)

### Writing READMEs
<details>
<summary>expand/collapse</summary>
<br>

- [x] [makeareadme.com](https://www.makeareadme.com/)
- [ ] [bulldogjob](https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project)
- [ ] [meakaakka](https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3)

### DevTools and the DOM
<details>
<summary>expand/collapse</summary>
<br>

- [x]  [How to inspect an element](https://www.lifewire.com/get-inspect-element-tool-for-browser-756549)
- [ ] [inspecting-the-dom](https://hackyourfuturebelgium.github.io/inspecting-the-dom/)
- [ ] [Modify the DOM. (does the source change?)](https://zapier.com/blog/inspect-element-tutorial/)

### HTML & CSS
<details>
<summary>expand/collapse</summary>
<br>

- [ ] FCC, Responsive Web Design: [exercises](https://www.freecodecamp.org/learn), https://www.youtube.com/watch?v=srvUrASNj0s
- [ ] [mmtuts: HTML & CSS](https://www.youtube.com/watch?v=TKYsuU86-DQ&list=PL0eyrZgxdwhwNC5ppZo_dYGVjerQY3xYU)
- [ ] CSS Games
- [ ] 🥚 [html-css-git-exercises](https://github.com/hackyourfuturebelgium/html-css-git-exercises)
- [ ] 🐣 [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
- [ ] 🐥 [css-exercises](https://github.com/dangodev/css-exercises)

### Collaborating on GitHub
<details>
<summary>expand/collapse</summary>
<br>

- [x] [Adding collaborators to a repository](https://www.youtube.com/watch?v=p49LRx3hYI8)
- [ ] [about code reviews](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews)
- [ ] [requesting a code review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)
- [ ] [Git Workflow for 2](https://github.com/hackyourfuturebelgium/git-workflow-workshop-for-two)
- [x] [Pull Requests](https://www.youtube.com/watch?v=2M16faxEQsg)
- [x] [Git & GitHub for Poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
- [ ] The Net Ninja: [11](https://www.youtube.com/watch?v=MnUd31TvBoU&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=11)
- [ ] linking PRs to Issues: [reference 1](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), [reference 2](https://help.github.com/articles/autolinked-references-and-urls/)
- [ ] [closing Issues using keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)

### User Stories
<details>
<summary>expand/collapse</summary>
<br>

- [ ] [User Stories](https://www.youtube.com/watch?v=apOvF9NVguA)
- [ ] Acceptance Criteria
        - [Yodiz](https://www.yodiz.com/blog/user-stories-acceptance-definition-and-criteria-in-agile-methodologies/)
        - [Zepel](https://zepel.io/agile/acceptance-criteria-for-user-stories/)
        - [Ruby Garage](https://rubygarage.org/blog/clear-acceptance-criteria-and-why-its-important)
        - [The Infinity Project](https://www.youtube.com/watch?v=KYS0ptJ4JWc)
- [ ]  Setting Priorities
        - [Many Strategies](https://zapier.com/blog/how-to-prioritize)
        - The Priority Quadrant
            - [The Quadrant](https://www.youtube.com/watch?v=NGvsxPOmWuw)
            - [Problems with this method](Problems with this method)
        - Other Perspectives
            - [Alex Ponomarev](https://medium.com/swlh/prioritizing-user-stories-in-agile-projects-d1dd8dd79165)
            - [Michael Lant](https://medium.com/swlh/prioritizing-user-stories-in-agile-projects-d1dd8dd79165)
---

Week 1

- [x] started the exercises
- [x] [project issue](https://github.com/HackYourFutureBelgium/class-13-14/issues/81)

#### I Need Help With:
I think I'm OK for now
#### What went well?
The communication with the team and the coach is excellent.

#### What went less well?
Maybe the time of each member to read more the instructions

**Comment by perezrei** [comment]
Initial commit

**Comment by perezrei** [comment]
adding links

**Comment by colevandersWands** [comment]
> Maybe the time of each member to read more the instructions

And some more time to practice, reading the instructions 100 times isn't going to help everyone.  It's a lot of theory in a very short time, hopefully the coming weeks will help put everything in perspective.

That and the communication!  👍 on your group work this week

**Comment by colevandersWands** [comment]
>  So far I'm not having trouble to understand the instructions once that I find them. Sometimes it's hard for me to look for them though it's just the first week. 

What's the most difficult things to find?  any tips for making everything easier to navigage?

**Comment by perezrei** [comment]
The most difficult thing is to understand 100% the tasks that we have to do. The sample is that we have all presented different things at this check-in and I don't think it's just the fact that not all of us have reached the same goals so far, but that everyone interprets them differently.

On the other hand, it's our first week, so I don't worry too much because I'm sure we'll learn to do better every week. Maybe it's the little experience using GitHub. Perhaps it is also the habit of looking for things on websites where there are menus and things that make our lives easier and we get used to that.

I am not saying that it is not like that in the repositories but sometimes I see even the same coaches going back and forth to get the information they want to show. Maybe later an idea occurs to me to contribute, I really would like that but for now I must understand more about the weekly routine to be able to offer some collaboration.

**Comment by colevandersWands** [comment]
> Perhaps it is also the habit of looking for things on websites where there are menus and things that make our lives easier and we get used to that.

:octocat: github sure isn't easy to figure out unless you already know what you're looking for

**Comment by colevandersWands** [comment]
> Maybe later an idea occurs to me to contribute, I really would like that but for now I must understand more about the weekly routine to be able to offer some collaboration.

let me know when you do! I'll be ready

**Comment by perezrei** [comment]
> > Perhaps it is also the habit of looking for things on websites where there are menus and things that make our lives easier and we get used to that.
> 
> :octocat: github sure isn't easy to figure out unless you already know what you're looking for

That's true. That's why I want to wait to figure out if I could suggest something to help.

**Comment by perezrei** [comment]
> > Maybe later an idea occurs to me to contribute, I really would like that but for now I must understand more about the weekly routine to be able to offer some collaboration.
> 
> let me know when you do! I'll be ready

Sure, you can count on that

**Comment by perezrei** [comment]
Hello , I'm fine now. Yesterday I was a little confused with the class names of hackyourfuture.be. My coach @Tamer has made an excellent work. He's always onto the group and he's always ready to help.

**Comment by perezrei** [comment]
Editing issue name

**Comment by colevandersWands** [comment]
@perezrei , I see you've added the `week-2` label but I don't see a new check-in for this week, could you answer the same questions as last week?  It's hard to know what you could use help with if we don't know what you're working on!  you can check out #89 as an example

**Comment by perezrei** [comment]
# Week 2

## Check-In

### I Need Help With:
**Git & GitHub**: I need continuously the tips you are giving us.

### What went well?
When I started the Technical Assignment It was my first contact with html and css. I realized this week that if we don't practice we can forget things easily but at the end of the week I felt really comfortable coding again.

### What went less well?
 I think the members of the group were struggling with their own troubles with coding and that situation caused a bad communication. The communication with the coach is still going great.

### Lessons Learned

**Comment by perezrei** [comment]
#  Week 3

## Group Issue
- [x] started the exercises 
- [x] [Group issue](https://github.com/Fatihayoz/HYF-Website)

## Check-In

### I Need Help With: 

I'm ok with html/css.  I was failing to fully understand all the steps of incremental-development. I feel confident so, for now, I'm ok. I'm always optimistic :ok_hand:

### What went well?

This week I finally got very comfortable with incremental development. I did the backlog, development-strategy, project-board and wireframe. Communication and advisory from my coach was very decisive.  I understand very well how useful is to relate issues with everything we do in the project. 

### What went less well?

Nothing really. I have not coded so much because what I've learned was more important to me at this moment. I have time for coding in the next 3 days.

### Lessons Learned

All the steps of planning are 100% clear: backlog, development-strategy, project-board and wireframe. There are still a lot of work to do but feeling great :punch:

**Comment by colevandersWands** [comment]
🚀 @perezrei !  Happy to see it all pulled together this week.  You're right to focus on the incremental development, there will be plenty of time to practice HTML/CSS this week and in the next module.

**Comment by perezrei** [comment]
Thank you very much for your comments Evan, they encourage me to continue discovering the different options that GitHub offers as a collaboration tool.

**Comment by perezrei** [comment]
I need to add that the advice of our coach @Tamer has been extremely important to understand day by day the operation and the usefulness of the issues, milestones, project board, etc.

**Comment by perezrei** [comment]
Issue closing
